M48
; DRILL file {KiCad (6.0.10)} date Tue Feb 14 22:37:04 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-14T22:37:04+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X130.525Y-59.67
X130.525Y-64.67
T2
X95.67Y-55.191
X95.67Y-58.191
T3
X97.0Y-48.0
X97.0Y-82.917
X132.0Y-48.0
X132.0Y-83.0
T0
M30
